name: Build Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Move to Docs Folder
        run: |
          mkdir -p docs
          mv dist/my-angular-project/browser/* docs/
        if: success()

      - name: Debug Info
        run: |
          ls -al
          echo "Current Directory: $(pwd)"
          echo "Contents of docs directory: $(ls -al docs)"
        if: always()
